export enum MoreCommandTypes {
  SUB_COMMAND = "SUB_COMMAND",
  SUB_COMMAND_GROUP = "SUB_COMMAND_GROUP",
  STRING = "STRING",
  INTEGER = "INTEGER",
  BOOLEAN = "BOOLEAN",
  ROLE = "ROLE",
  MENTIONABLE = "MENTIONABLE",
  NUMBER = "NUMBER",
}
